'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@mui/material/styles';
import theme from "./theme";
import ReactQueryProvider from "./react-query-provider";
import 'react-loading-skeleton/dist/skeleton.css'
import { Divider, Tab, Tabs } from "@mui/material";
import React from "react";
import { Navigation } from "./navigation/navigation";



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <link rel="preconnect" href="https://rsms.me/"></link>
      <link rel="stylesheet" href="https://rsms.me/inter/inter.css"></link>
        <body>
          <ThemeProvider theme={theme}>
            <ReactQueryProvider>
              <Navigation/>
              <Divider/>
              {children}
            </ReactQueryProvider>
          </ThemeProvider>
        </body>
    </html>
  );
}
